jira:
  url: ${JIRA_URL}
  path: /rest/api
  login: ${JIRA_LOGIN}
  password: ${JIRA_PASSWORD}
  project: ${JIRA_PROJECT}

notion:
  url: https://api.notion.com
  path: /
  timesheetDb: ${NOTION_DB}
  secret: ${NOTION_SECRET}

logging:
  level:
    es.e1sordo.worklog_sync.clients:
      JiraClient: DEBUG # Feign logging only responds to the DEBUG level
      NotionClient: DEBUG # Feign logging only responds to the DEBUG level
    root: INFO
